pins vscode and lsp package versions coherently
the compatibility tests (and using the plugin with any version
<1.82.0) currently fails with
Error: The language client requires VS Code version ^1.82.0 but received version 1.63.1
This commit pins the versions so that doesn't occur anymore.

Rationale for the versions:

We need at least @types/vscode=~1.67.0 to use the newer client start api:

const client: LanguageClient = ...;
await client.start();

instead of

const client: LanguageClient = ...;
client.start();
await client.onReady();

and the LanguageClient#dispose method.

But @types/vscode=~1.67.0 has an issue where running tests
modifies the package.json (https://github.com/microsoft/vscode/issues/148975)
which is fixed in ~1.71.0.

The LSP packages are then selected to keep backwards compatibility with
~1.71.0

Signed-off-by: Lukas Bockstaller <lukas.bockstaller@posteo.de>