Pin and test all vscode packages (#899)
* test stated version compatibility

this commit adds a new testing mode whereby the extension
is tested against the stated minimum vscode compatibility

this test fails in this commit due to a minimum @types/vscode
requirement of the lsp packages that breaks during runtime

Signed-off-by: Lukas Bockstaller <lukas.bockstaller@posteo.de>

* pins vscode and lsp package versions coherently

the compatibility tests (and using the plugin with any version
<1.82.0) currently fails with
Error: The language client requires VS Code version ^1.82.0 but received version 1.63.1
This commit pins the versions so that doesn't occur anymore.

Rationale for the versions:

We need at least @types/vscode=~1.67.0 to use the newer client start api:

const client: LanguageClient = ...;
await client.start();

instead of

const client: LanguageClient = ...;
client.start();
await client.onReady();

and the LanguageClient#dispose method.

But @types/vscode=~1.67.0 has an issue where running tests
modifies the package.json (https://github.com/microsoft/vscode/issues/148975)
which is fixed in ~1.71.0.

The LSP packages are then selected to keep backwards compatibility with
~1.71.0

Signed-off-by: Lukas Bockstaller <lukas.bockstaller@posteo.de>

* adds missing sinon types

Signed-off-by: Lukas Bockstaller <lukas.bockstaller@posteo.de>

* Remove svg image links

Signed-off-by: Zabil Cheriya Maliackal <zabilcm@gmail.com>

* bumps version for release

Signed-off-by: Lukas Bockstaller <lukas.bockstaller@posteo.de>

* removes direct dependency to vscode-jsonrpc and vscode-languageclient-protocol

Signed-off-by: Lukas Bockstaller <lukas.bockstaller@posteo.de>

* bumps test timeout

Signed-off-by: Lukas Bockstaller <lukas.bockstaller@posteo.de>

* De-duplicate transitive dependencies

Signed-off-by: Chad Wilson <chadw@thoughtworks.com>

* Simplify dependabot grouping rules

Signed-off-by: Chad Wilson <chadw@thoughtworks.com>

---------

Signed-off-by: Lukas Bockstaller <lukas.bockstaller@posteo.de>
Signed-off-by: Zabil Cheriya Maliackal <zabilcm@gmail.com>
Signed-off-by: Chad Wilson <chadw@thoughtworks.com>
Co-authored-by: Zabil Cheriya Maliackal <zabilcm@gmail.com>
Co-authored-by: Chad Wilson <chadw@thoughtworks.com>